// frontend-svelte/src/routes/login/+page.svelte
<script>
  import { auth } from '$lib/stores/auth.svelte.js';
  import { goto } from '$app/navigation';
  import Icon from '$lib/components/ui/Icon.svelte';
  import { toast } from 'svelte-sonner';

  let correo = $state('gerencia@mfn.gob.gt');
  let contrasena = $state('mfn2026');
  let loading = $state(false);

  const ROLES_DEMO = [
    { label: 'Gerente Ejecutivo', correo: 'gerencia@mfn.gob.gt' },
    { label: 'Junta Directiva', correo: 'juntadirectiva@mfn.gob.gt' },
    { label: 'Dir. Administrativa', correo: 'diradmin@mfn.gob.gt' }
  ];

  function seleccionarRol(r) {
    correo = r.correo;
    contrasena = 'mfn2026';
  }

  async function onSubmit(e) {
    e?.preventDefault();
    loading = true;
    try {
      await auth.login(correo, contrasena);
      toast.success('Sesión iniciada correctamente');
      goto('/');
    } catch (err) {
      console.error('Error de autenticación:', err);
      const msg = err.response?.data?.error || err.message || 'Error de conexión con el servidor';
      toast.error(`Error al iniciar sesión: ${msg}`);
    } finally {
      loading = false;
    }
  }
</script>

<svelte:head>
  <title>Acceso al Sistema | MFN Digital</title>
</svelte:head>

<div class="min-h-screen bg-[#F4F7FA] flex items-center justify-center p-6 text-[#0A1526]">
  <div class="w-full max-w-md bg-white shadow-[0_20px_60px_-15px_rgba(10,21,38,0.06)] rounded-[32px] p-8 md:p-10 border border-gray-100/60 animate-fade-in">
    <div class="flex flex-col items-center mb-8">
      <div class="w-14 h-14 rounded-2xl bg-[#0A1526] flex items-center justify-center text-amber-400 shadow-md mb-4">
        <Icon name="account_balance" className="w-7 h-7" />
      </div>
      <div class="flex items-center gap-1.5 mb-1">
        <span class="text-[9px] font-extrabold uppercase tracking-[0.15em] text-[#0A1526]">MFN Digital</span>
        <span class="w-1.5 h-1.5 rounded-full bg-emerald-500 inline-block"></span>
      </div>
      <h1 class="text-[20px] font-black tracking-tight text-[#0A1526] text-center">
        Mancomunidad Frontera del Norte
      </h1>
      <p class="text-[12px] text-[#0A1526]/50 mt-1 text-center font-medium">
        Plataforma de Gestión Operativa e Intermunicipal (Capítulo IV)
      </p>
    </div>

    <!-- Cuentas de demostración rápida -->
    <div class="mb-5 p-3 rounded-2xl bg-[#F8FAFC] border border-gray-100">
      <span class="text-[9px] font-extrabold uppercase tracking-wider text-[#0A1526]/40 block mb-2 text-center">
        Seleccionar Rol Preconfigurado
      </span>
      <div class="flex items-center justify-center gap-1.5 flex-wrap">
        {#each ROLES_DEMO as r}
          <button 
            type="button" 
            onclick={() => seleccionarRol(r)}
            class="text-[10px] font-bold px-2.5 py-1 rounded-full transition-all {correo === r.correo ? 'bg-[#0A1526] text-white shadow-xs' : 'bg-white text-[#0A1526]/70 border border-gray-200 hover:border-[#3B82F6]'}"
          >
            {r.label}
          </button>
        {/each}
      </div>
    </div>

    <form onsubmit={onSubmit} class="space-y-4">
      <div>
        <label class="block text-[10px] font-bold uppercase tracking-[0.15em] text-[#0A1526]/40 mb-1.5">
          Correo Institucional
        </label>
        <input 
          type="email" 
          bind:value={correo} 
          required 
          disabled={loading}
          class="w-full bg-[#F4F7FA] border border-gray-100 rounded-xl px-4 py-3 text-[13px] text-[#0A1526] focus:outline-none focus:border-[#3B82F6] focus:ring-1 focus:ring-[#3B82F6] transition-all disabled:opacity-50" 
        />
      </div>

      <div>
        <label class="block text-[10px] font-bold uppercase tracking-[0.15em] text-[#0A1526]/40 mb-1.5">
          Contraseña
        </label>
        <input 
          type="password" 
          bind:value={contrasena} 
          required 
          disabled={loading}
          class="w-full bg-[#F4F7FA] border border-gray-100 rounded-xl px-4 py-3 text-[13px] text-[#0A1526] focus:outline-none focus:border-[#3B82F6] focus:ring-1 focus:ring-[#3B82F6] transition-all disabled:opacity-50" 
        />
      </div>

      <button 
        type="submit" 
        disabled={loading}
        class="w-full bg-[#0A1526] hover:bg-black text-white font-bold py-3.5 rounded-full text-[13px] shadow-md transition-colors mt-6 flex items-center justify-center gap-2 disabled:opacity-60 cursor-pointer"
      >
        {#if loading}
          <div class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
          <span>Validando credenciales...</span>
        {:else}
          <span>Ingresar al Sistema MFN</span>
          <Icon name="arrow_forward" className="w-4 h-4 text-[#3B82F6]" />
        {/if}
      </button>
    </form>

    <div class="mt-6 text-center">
      <a 
        href="/transparencia" 
        class="text-[12px] font-bold text-[#3B82F6] hover:underline inline-flex items-center gap-1"
      >
        <Icon name="public" className="w-4 h-4" />
        <span>Ir al Portal Ciudadano de Transparencia (Sin Clave)</span>
      </a>
    </div>

    <div class="mt-8 pt-6 border-t border-gray-100 text-center">
      <p class="text-[10px] font-bold uppercase tracking-[0.1em] text-[#0A1526]/30">
        Jurisdicción Activa · 6 Municipios Miembros
      </p>
      <p class="text-[11px] font-medium text-[#0A1526]/50 mt-1">
        San Pedro Soloma · Santa Eulalia · San Rafael la Independencia
      </p>
    </div>
  </div>
</div>

// frontend/src/pages/Login.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { useAuth, ROLES } from '../context/AuthContext';
import Button from '../components/ui/Button';
import Input from '../components/ui/Input';
import { Halos, Icon } from '../components/ui/Glass';
import useGlassSpecular from '../hooks/useGlassSpecular';

const DEMO_GROUPS = [
  {
    titulo: 'Gobierno & Dirección',
    cuentas: [
      { rol: 'JD', correo: 'juntadirectiva@mfn.gob.gt' },
      { rol: 'GE', correo: 'gerencia@mfn.gob.gt' },
    ],
  },
  {
    titulo: 'Administración & Control',
    cuentas: [
      { rol: 'RRHH', correo: 'rrhh@mfn.gob.gt' },
      { rol: 'DIRADMIN', correo: 'diradmin@mfn.gob.gt' },
      { rol: 'AUD', correo: 'auditoria@mfn.gob.gt' },
      { rol: 'DIRPROY', correo: 'dirproyectos@mfn.gob.gt' },
    ],
  },
  {
    titulo: 'Jefaturas & Personal',
    cuentas: [
      { rol: 'JI', correo: 'jefatura@mfn.gob.gt' },
      { rol: 'EMP', correo: 'empleado@mfn.gob.gt' },
    ],
  },
];

export default function Login() {
  useGlassSpecular();
  const { login } = useAuth();
  const navigate = useNavigate();
  const [correo, setCorreo] = useState('');
  const [contrasena, setContrasena] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const doLogin = async (email, pass) => {
    setLoading(true);
    setError('');
    try {
      const user = await login(email, pass);
      toast.success(`Bienvenido/a, ${user.nombre}`);
      navigate('/');
    } catch (err) {
      setError(err.response?.data?.error || 'No se pudo iniciar sesión. Verifique que el backend esté corriendo en el puerto 8080.');
    } finally {
      setLoading(false);
    }
  };

  const onSubmit = (e) => {
    e.preventDefault();
    doLogin(correo, contrasena);
  };

  return (
    <div className="admin-light min-h-screen bg-paper relative flex items-center justify-center p-4 md:p-8 overflow-hidden">
      <Halos variant="section" />
      <div className="relative z-10 w-full max-w-lg">
        <div className="glass-light rounded-[32px] p-8 md:p-10 shadow-card-lg animate-rise">
          {/* Logo y Encabezado */}
          <div className="flex flex-col items-center mb-7">
            <div className="relative mb-3">
              <span className="grid place-items-center w-16 h-16 rounded-2xl bg-gradient-to-br from-bg to-bg-soft shadow-card border border-white/20">
                <span className="text-white font-black text-20 tracking-wider">MFN</span>
              </span>
            </div>
            <h1 className="text-22 font-black tracking-tightish text-bg text-center">
              SIRH · Mancomunidad Frontera del Norte
            </h1>
            <p className="text-13 text-bg/60 mt-1 text-center max-w-sm">
              Sistema de Información para la Gestión de Recursos Humanos (Capítulo V)
            </p>
          </div>

          {/* Formulario */}
          <form onSubmit={onSubmit} className="space-y-4">
            <Input
              label="Correo institucional"
              type="email"
              value={correo}
              onChange={(e) => setCorreo(e.target.value)}
              placeholder="usuario@mfn.gob.gt"
              required
            />
            <Input
              label="Contraseña"
              type="password"
              value={contrasena}
              onChange={(e) => setContrasena(e.target.value)}
              placeholder="••••••••"
              required
            />
            {error && (
              <div className="p-3 rounded-xl bg-rose/10 border border-rose/20 text-13 font-semibold text-rose flex items-center gap-2">
                <Icon name="error" className="w-4 h-4 shrink-0" />
                <span>{error}</span>
              </div>
            )}
            <Button type="submit" variant="filled" size="lg" className="w-full font-bold" disabled={loading}>
              {loading ? 'Validando credenciales…' : 'Ingresar al Sistema'}
            </Button>
          </form>

          {/* Selector de Cuentas Demo por Roles */}
          <div className="mt-8 pt-6 border-t border-bg/10">
            <div className="flex items-center justify-between mb-3">
              <p className="text-11 font-extrabold uppercase tracking-widest text-bg/40">
                Acceso Rápido · Cuentas de Demostración
              </p>
              <span className="text-11 font-mono text-celeste-hov bg-celeste/10 px-2 py-0.5 rounded-md font-bold">
                clave: mfn2026
              </span>
            </div>

            <div className="space-y-3">
              {DEMO_GROUPS.map((g) => (
                <div key={g.titulo}>
                  <span className="text-10 font-bold uppercase tracking-wider text-bg/30 block mb-1.5 ml-1">
                    {g.titulo}
                  </span>
                  <div className="grid grid-cols-2 gap-1.5">
                    {g.cuentas.map((d) => (
                      <button
                        key={d.rol}
                        type="button"
                        onClick={() => {
                          setCorreo(d.correo);
                          setContrasena('mfn2026');
                          doLogin(d.correo, 'mfn2026');
                        }}
                        disabled={loading}
                        className="flex flex-col items-start px-3 py-2 rounded-xl text-left text-bg/75 bg-bg/[0.03] hover:bg-bg/8 hover:text-bg transition-all border border-bg/5 hover:border-bg/10 disabled:opacity-50 group"
                      >
                        <span className="text-12 font-bold leading-tight group-hover:text-celeste-hov transition-colors">
                          {ROLES[d.rol]?.label || d.rol}
                        </span>
                        <span className="text-bg/35 font-mono text-10 mt-0.5 truncate w-full">
                          {d.correo}
                        </span>
                      </button>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
